config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'articles', to: 'articles#index'
  get 'articles/new', to: 'articles#new'
  post 'articles', to: 'articles#create'
  get 'articles/:id', to: 'articles#show', as: :article
  get 'article/:id/edit', to: 'articles#edit', as: :edit
  patch 'articles/:id', to: 'articles#update'
  delete 'articles/:id', to: 'articles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <h1>Add new Article </h1>
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.submit :update, class: "btn btn-primary"%>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
<h1>Articles</h1>
<ul class="list-group">
<% @articles.each do |article| %>
<%=link_to article.title , article_path(article), :class => "list-group-item list-group-item-action" %>
<% end %>
<p><%= link_to "Add a new article", articles_new_path, class: "btn btn-primary mt-3" %></p>
</ul>

</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>Add new Article </h1>
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.submit :post, class: "btn btn-primary"%>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1> <%=  @article.title %></h1>
  <p><%=  @article.content %></p>
  <p><%= link_to "update the article", edit_path %></p>
  <p><%= link_to "Delete",
              article_path(@article),
              method: :delete,
              data: { confirm: "Are you sure?" } %></p>
  <p><%= link_to "back to index", articles_path %></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>